global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts-podorozniy'
