version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      mongodb-exporter-network:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: podorozniy/ui:${VERSION_UI}
    ports:
      - ${PORT}:${PORT}/${PROTOCOL}
    networks:
      - front_net
  post:
    image: podorozniy/post:${VERSION_POST}
    networks:
      - front_net
      - back_net
  comment:
    image: podorozniy/comment:${VERSION_COMMENT}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - '9100:9100'
    networks:
      - front_net
      - back_net

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    environment: 
      - MONGODB_URI=mongodb://mongo_db:27017
    networks:
      - mongodb-exporter-network
      - back_net

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - '9115:9115'
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
  mongodb-exporter-network:
