version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: podorozniy/ui:${VERSION_UI}
    ports:
      - ${PORT}:${PORT}/${PROTOCOL}
    networks:
      - front_net
  post:
    build: ./post-py
    image: podorozniy/post:${VERSION_POST}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: podorozniy/comment:${VERSION_COMMENT}
    networks:
      - front_net
      - back_net
volumes:
  post_db:

networks:
  front_net:
  back_net:
