version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: podorozniy/elasticsearch:${VERSION_ELASTIC}
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.4.2
    ports:
      - "5601:5601"
